[package]
name = "libmnemo"
version = "0.0.1"
edition = "2021"

[lib]
name = "libmnemo"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }


[features]
debug = []
web = []